# Generated by Django 3.2.4 on 2021-06-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='Full_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='Password',
            new_name='password',
        ),
    ]
